
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.decorators import api_view, permission_classes


@api_view(['GET','POST'])
@permission_classes([IsAuthenticated])
def testEndPoint(request):
    if request.method == 'GET':
        data = f"Response generated by API for {request.user}"
        return Response({'response':data}, status=status.HTTP_200_OK)
    return Response({},status.HTTP_400_BAD_REQUEST)